#!/usr/bin/env bash
#
# Parses DHCP options from openvpn to update resolv.conf
# To use set as 'up' and 'down' script in your openvpn *.conf:
# up /etc/openvpn/update-resolv-conf
# down /etc/openvpn/update-resolv-conf
#
# Used snippets of resolvconf script by Thomas Hood <jdthood@yahoo.co.uk>
# and Chris Hanson
# Licensed under the GNU GPL.  See /usr/share/common-licenses/GPL.
# 07/2013 colin@daedrum.net Fixed intet name
# 05/2006 chlauber@bnc.ch
#
# Example envs set from openvpn:
# foreign_option_1='dhcp-option DNS 193.43.27.132'
# foreign_option_2='dhcp-option DNS 193.43.27.133'
# foreign_option_3='dhcp-option DOMAIN be.bnc.ch'
# foreign_option_4='dhcp-option DOMAIN-SEARCH bnc.local'

## The 'type' builtins will look for file in $PATH variable, so we set the
## PATH below. You might need to directly set the path to 'resolvconf'
## manually if it still doesn't work, i.e.
## RESOLVCONF=/usr/sbin/resolvconf
export PATH=$PATH:/sbin:/usr/sbin:/bin:/usr/bin
#RESOLVCONF=$(type -p resolvconf)

case $script_type in

up)
# lets create a clean resolv.conf backup, as down works inconsistently on host shutdown and reboots. If host upstream dns servers are changed please remove /etc/resolv.conf.connman-backup, so it can be replaced. 
if [ ! -f /etc/resolv.conf.connman-backup ]; then
    cp -af /etc/resolv.conf /etc/resolv.conf.connman-backup
fi

cp -af /etc/resolv.conf /dev/shm/ #backup of resolv.conf so can be restored on service restarts

# -----------------------
# Parse OpenVPN pushed options
# -----------------------
for optionname in ${!foreign_option_*}; do
    option="${!optionname}"

    part1=$(echo "$option" | cut -d " " -f 1)

    if [ "$part1" = "dhcp-option" ]; then
        part2=$(echo "$option" | cut -d " " -f 2)
        part3=$(echo "$option" | cut -d " " -f 3)

        if [ "$part2" = "DNS" ]; then
            IF_DNS_NAMESERVERS="$IF_DNS_NAMESERVERS $part3"
        fi

        if [ "$part2" = "DOMAIN" ] || [ "$part2" = "DOMAIN-SEARCH" ]; then
            IF_DNS_SEARCH="$IF_DNS_SEARCH $part3"
        fi
    fi
done


# -----------------------
# Build ConnMan DNS string
# -----------------------
R=""
for NS in $IF_DNS_NAMESERVERS; do
    R="$R $NS"
done
R=$(echo "$R" | sed 's/^ *//')

IFACE=$(connmanctl services | awk '/\*AR Wired/ {print $NF}')

# -----------------------
# Push DNS to ConnMan
# -----------------------
if [ -n "$R" ]; then
    connmanctl config "$IFACE" --nameservers $R
else
    echo "no dns server's pushed"
fi

# -----------------------
# Handle search domains
# -----------------------
if [ -n "$IF_DNS_SEARCH" ]; then
    S="search $IF_DNS_SEARCH"
    printf "%s\n" "$S" > /etc/resolv.conf
    echo "domain pushed from VPN: $IF_DNS_SEARCH"
else
    echo "no domain pushed from VPN"
fi

;;
down)
  mv /dev/shm/resolv.conf /etc/
  ;;
esac
exit 0
