#!/usr/bin/env bash
#
# Parses DHCP options from openvpn to update resolv.conf
# To use set as 'up' and 'down' script in your openvpn *.conf:
# up /etc/openvpn/connman-update-resolv
# down /etc/openvpn/connman-update-resolv
#
# Used snippets of resolvconf script by Thomas Hood <jdthood@yahoo.co.uk>
# and Chris Hanson
# Licensed under the GNU GPL.  See /usr/share/common-licenses/GPL.
# 07/2013 colin@daedrum.net Fixed intet name
# 05/2006 chlauber@bnc.ch
#
# Example envs set from openvpn:
# foreign_option_1='dhcp-option DNS 193.43.27.132'
# foreign_option_2='dhcp-option DNS 193.43.27.133'
# foreign_option_3='dhcp-option DOMAIN be.bnc.ch'
# foreign_option_4='dhcp-option DOMAIN-SEARCH bnc.local'

## The 'type' builtins will look for file in $PATH variable, so we set the
## PATH below. You might need to directly set the path to 'resolvconf'
## manually if it still doesn't work, i.e.
## RESOLVCONF=/usr/sbin/resolvconf
export PATH=$PATH:/sbin:/usr/sbin:/bin:/usr/bin
#RESOLVCONF=$(type -p resolvconf)

case $script_type in

up)
#------------------------
# Store Pre-vpn DNS
#------------------------
IFACE=$(connmanctl services | awk '/^\*/ {print $NF; exit}')

# Capture only once per VPN session
if [ ! -f /etc/resolv.conf.connman-backup ]; then
    PRE_VPN_DNS=$(connmanctl services "$IFACE" \
        | sed -n 's/.*Nameservers\.Configuration = \[\(.*\)\].*/\1/p' \
        | tr -d ',' \
        | xargs)

    if [ -n "$PRE_VPN_DNS" ]; then
        echo "$PRE_VPN_DNS" > /etc/resolv.conf.connman-backup
    fi
fi

# -----------------------
# Parse OpenVPN pushed options
# -----------------------
for optionname in ${!foreign_option_*}; do
    option="${!optionname}"

    part1=$(echo "$option" | cut -d " " -f 1)

    if [ "$part1" = "dhcp-option" ]; then
        part2=$(echo "$option" | cut -d " " -f 2)
        part3=$(echo "$option" | cut -d " " -f 3)

        if [ "$part2" = "DNS" ]; then
            IF_DNS_NAMESERVERS="$IF_DNS_NAMESERVERS $part3"
        fi

        if [ "$part2" = "DOMAIN" ] || [ "$part2" = "DOMAIN-SEARCH" ]; then
            IF_DNS_SEARCH="$IF_DNS_SEARCH $part3"
        fi
    fi
done


# -----------------------
# Build ConnMan DNS string
# -----------------------
R=""
for NS in $IF_DNS_NAMESERVERS; do
    R="$R $NS"
done
R=$(echo "$R" | sed 's/^ *//')

# -----------------------
# Push DNS to ConnMan
# -----------------------
if [ -n "$R" ]; then
    connmanctl config "$IFACE" --nameservers $R
else
    echo "no dns server's pushed"
fi

;;
down)
IFACE=$(connmanctl services | awk '/^\*/ {print $NF; exit}')

if [ -f /etc/resolv.conf.connman-backup ]; then
    PRE_VPN_DNS=$(cat /etc/resolv.conf.connman-backup)

    if [ -n "$PRE_VPN_DNS" ] && [ -n "$IFACE" ]; then
        connmanctl config "$IFACE" --nameservers $PRE_VPN_DNS
    fi
fi
;;
esac
exit 0
